services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]

    contao.listener.backend_locale:
        class: Contao\CoreBundle\EventListener\BackendLocaleListener
        arguments:
            - '@security.helper'
            - '@translator'
        tags:
            # The priority must be lower than the one of the firewall listener (defaults to 8)
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 7 }

    contao.listener.backend_menu_listener:
        class: Contao\CoreBundle\EventListener\BackendMenuListener
        arguments:
            - '@security.helper'
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, method: onBuild }

    contao.listener.bypass_maintenance:
        class: Contao\CoreBundle\EventListener\BypassMaintenanceListener
        arguments:
            - '@contao.security.token_checker'
        tags:
            # The priority must be higher than the one of the Lexik maintenance bundle (defaults to 0)
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 6 }

    contao.listener.clear_session_data:
        class: Contao\CoreBundle\EventListener\ClearSessionDataListener
        tags:
            # The priority must be higher than the one of the Symfony save session listener (defaults to -1000)
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -768 }

    contao.listener.command_scheduler:
        class: Contao\CoreBundle\EventListener\CommandSchedulerListener
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@Contao\CoreBundle\Cron\Cron'
            - '%fragment.path%'
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.csrf_token_cookie:
        class: Contao\CoreBundle\EventListener\CsrfTokenCookieListener
        arguments:
            - '@contao.csrf.token_storage'
            - '%contao.csrf_cookie_prefix%'
        tags:
            # The priority must be higher than the one of the Symfony route listener (defaults to 32)
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 36 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    contao.listener.data_container_callback:
        class: Contao\CoreBundle\EventListener\DataContainerCallbackListener
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    contao.listener.doctrine_schema:
        class: Contao\CoreBundle\EventListener\DoctrineSchemaListener
        arguments:
            - '@contao.doctrine.schema_provider'
        tags:
            - { name: doctrine.event_listener, event: onSchemaIndexDefinition }
            - { name: doctrine.event_listener, event: postGenerateSchema }

    contao.listener.exception_converter:
        class: Contao\CoreBundle\EventListener\ExceptionConverterListener
        tags:
            # The priority must be higher than the one of the response exception listener (defaults to 64)
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 96 }

    contao.listener.insecure_installation:
        class: Contao\CoreBundle\EventListener\InsecureInstallationListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    contao.listener.insert_tags.asset:
        class: Contao\CoreBundle\EventListener\InsertTags\AssetListener
        arguments:
            - '@assets.packages'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }

    contao.listener.insert_tags.translation:
        class: Contao\CoreBundle\EventListener\InsertTags\TranslationListener
        arguments:
            - '@translator'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }

    contao.listener.locale:
        class: Contao\CoreBundle\EventListener\LocaleListener
        arguments:
            - '@translator'
            - '@contao.routing.scope_matcher'
            - '%contao.locales%'
        tags:
            # The priority must be lower than the one of the Symfony route listener (defaults to 32)
            # and higher than the Symfony locale listener (defaults to 16)
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20 }
            - { name: kernel.event_listener, event: kernel.request, method: setTranslatorLocale, priority: 100 }

    contao.listener.make_response_private:
        class: Contao\CoreBundle\EventListener\MakeResponsePrivateListener
        tags:
            # The priority must be lower than the one of MergeHttpHeadersListener (defaults to 256)
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    contao.listener.merge_http_headers:
        class: Contao\CoreBundle\EventListener\MergeHttpHeadersListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 256 }
            - { name: kernel.reset, method: reset }

    contao.listener.pretty_error_screens:
        class: Contao\CoreBundle\EventListener\PrettyErrorScreenListener
        arguments:
            - '%contao.pretty_error_screens%'
            - '@twig'
            - '@contao.framework'
            - '@security.helper'
        tags:
            # The priority must be higher than the one of the Twig exception listener (defaults to -128)
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -96 }

    contao.listener.referer_id:
        class: Contao\CoreBundle\EventListener\RefererIdListener
        arguments:
            - '@contao.token_generator'
            - '@contao.routing.scope_matcher'
        tags:
            # The priority must be lower than the one of the Symfony route listener (defaults to 32)
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20 }

    contao.listener.request_token:
        class: Contao\CoreBundle\EventListener\RequestTokenListener
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'
            - '%contao.csrf_cookie_prefix%'
        tags:
            # The priority must be lower than the one of the Symfony route listener (defaults to 32)
            # and the Symfony locale aware listener (defaults to 15)
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 14 }

    contao.listener.response_exception:
        class: Contao\CoreBundle\EventListener\ResponseExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 64 }

    contao.listener.robots_txt:
        class: Contao\CoreBundle\EventListener\RobotsTxtListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, event: contao.robots_txt, method: onRobotsTxt }

    contao.listener.search_index:
        class: Contao\CoreBundle\EventListener\SearchIndexListener
        arguments:
            - '@contao.search.indexer'
            - '%fragment.path%'
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.store_referer:
        class: Contao\CoreBundle\EventListener\StoreRefererListener
        arguments:
            - '@security.helper'
            - '@contao.routing.scope_matcher'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    contao.listener.subrequest_cache:
        class: Contao\CoreBundle\EventListener\SubrequestCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -255 }
            - { name: kernel.reset, method: reset }

    contao.listener.switch_user:
        class: Contao\CoreBundle\EventListener\SwitchUserListener
        arguments:
            - '@security.token_storage'
            - '@logger'
        tags:
            - { name: kernel.event_listener, event: security.switch_user, method: onSwitchUser }

    contao.listener.two_factor.frontend:
        class: Contao\CoreBundle\EventListener\TwoFactorFrontendListener
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
            - '@security.token_storage'
            - '%scheb_two_factor.security_tokens%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    contao.listener.user_session:
        class: Contao\CoreBundle\EventListener\UserSessionListener
        arguments:
            - '@database_connection'
            - '@security.helper'
            - '@contao.routing.scope_matcher'
            - '@event_dispatcher'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
